### ISSUE TITLE
README suggestion: Refer to config.middleware.insert_before

### ISSUE THREAD

**Issue by olleolleolle** [downgba/rack-healthcheck#6]
Hi!

As a new user of the gem, following instructions, it can be confusing if other middlewares take action before rack-healthcheck can show status. 

If, in Rails, placed before `ActiveRecord::Migration::CheckPending` it works fine.

```ruby
     # Healthcheck
     config.middleware.insert_before ActiveRecord::Migration::CheckPending, Rack::Healthcheck::Middleware
```

Would you like a PR with this change?

**Comment by leandro-maduro** [comment]
Hi, yeah sure, can you open it?

thanks for the suggestion.

**Comment by Lewiscowles1986** [comment]
I've updated the PR to include named placement. I hope this satisfies most usage of the Gem within Rails. Perhaps `<details>` & `<summary>` blocks would help make the document shorter at the cost of lazy scanning.
